[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "llm-readme-gen"
version = "0.1.0"
description = "Generate README files from repositories using LLMs like DeepSeek"
authors = [{ name = "Sina Tavakkoli" }]
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["requests", "python-dotenv"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]